### ISSUE TITLE
Lancer ./minishell avec une redirection

### ISSUE THREAD

**Issue by Cpt-Graby** [JungoQuentin/minishell#5]
Attention, il pourrait y avoir des problèmes:
Un utilisateur lance minishell avec des redirections. 
Genre 2>
 ou << enfin voila... 

J'ai fait un petit patch dans le main.c... 
Mais pas sur que ça tienne.

**Comment by JungoQuentin** [comment]
Est-ce que c'est demander de gerer ce cas ?
